// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<void>;

export function ReadNote(arg1:string):Promise<main.Note>;

export function ReadNotesDir():Promise<Array<string>>;

export function RenameNote(arg1:string,arg2:string):Promise<void>;

export function WriteNote(arg1:string,arg2:string):Promise<void>;
