// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function ReadNote(arg1) {
  return window['go']['main']['App']['ReadNote'](arg1);
}

export function ReadNotesDir() {
  return window['go']['main']['App']['ReadNotesDir']();
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function WriteNote(arg1, arg2) {
  return window['go']['main']['App']['WriteNote'](arg1, arg2);
}
